### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by iBotPeaches**

### CODE REVIEW

**Review by toadbane — APPROVED** [review]

**Review by toadbane — CHANGES_REQUESTED** [review]
The code looked fine to me, but there is a build error. Looks like there is a lot going on in it, so not sure.

**Comment by iBotPeaches** [comment]
> The code looked fine to me, but there is a build error. Looks like there is a lot going on in it, so not sure.

Yeah I was attempting to upstream a PR to this repo to help out, but it looks like building node dependencies has some issues so backlogged it.

**Comment by iBotPeaches** [comment]
Bringing this back.

**Comment by iBotPeaches** [comment]
Okay, this is a lot of stuff. I basically started getting CI to work on Actions vs TravisCI. Saw Jest was like 4 years out of date, then updated that and syntax was failing new linter. So went crazy.

Stuck with 2 failing tests, unsure at present. @ian-wd - lets see if we can fix those and even remove the "anti-ci" checks, because GitHub CI I think is far superior to Travis so I believe it will work.

**Comment by iBotPeaches** [comment]
Okay, this is a lot of stuff. I basically started getting CI to work on Actions vs TravisCI. Saw Jest was like 4 years out of date, then updated that and syntax was failing new linter. So went crazy.

Stuck with 2 failing tests, unsure at present. @ian-wd - lets see if we can fix those and even remove the "anti-ci" checks, because GitHub CI I think is far superior to Travis so I believe it will work.

**Review by brianangulo — APPROVED** [review]

**Review by Vacoris — APPROVED** [review]

**Review by mkodell — APPROVED** [review]

**Pull request merged**
